@echo off

set DATA=SEVERITY=%SEVERITY%^
&COMPUTER=%COMPUTER%^
&DOMAIN=%DOMAIN%^
&EVENT=%EVENT%^
&DESCR=%DESCR%^
&RISE_TIME=%RISE_TIME%^
&KLCSAK_EVENT_TASK_DISPLAY_NAME=%KLCSAK_EVENT_TASK_DISPLAY_NAME%^
&KL_PRODUCT=%KL_PRODUCT%^
&KL_VERSION=%KL_VERSION%^
&KLCSAK_EVENT_SEVERITY_NUM=%KLCSAK_EVENT_SEVERITY_NUM%^
&HOST_IP=%HOST_IP%^
&HOST_CONN_IP=%HOST_CONN_IP%

curl -s -X POST -d "%DATA%" http://127.0.0.1:12345/event